import { useState, type FormEvent } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import AuthLayout from "../../layouts/AuthLayout";
import Input from "../../components/ui/Input";
import Button from "../../components/ui/Button";

export default function UpdateCredentials() {
    const location = useLocation();
    const navigate = useNavigate();
    const { currentEmail } = location.state || {};

    const [formData, setFormData] = useState({
        email: currentEmail || "email@gmail.com",
        currentPassword: "",
        newPassword: "",
        confirmPassword: "",
    });

    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setLoading(true);

        setTimeout(() => {
            setLoading(false);
            navigate("/login", {
                state: {
                    successMessage:
                        "Password updated. Please log in with your new credentials.",
                },
            });
        }, 1500);
    };

    return (
        <AuthLayout>
            <div className="mb-6">
                <h1 className="text-[32px] font-bold text-[#1F2937] mb-2 leading-tight ">
                    Update Your Credentials
                </h1>

                <p className="text-[#6B7280] text-sm leading-relaxed max-w-[350px]">
                    Protect your account by creating a new, personalized password
                    for your profile
                </p>
            </div>

            <div className="bg-[#FFF7ED] border border-[#FFEDD5] p-5 rounded-lg mb-8">
                <p className="text-[#9A3412] text-[13px] leading-relaxed">
                    <span className="font-bold">Security Action Required:</span>{" "}
                    Your current password was generated by an administrator. For
                    your protection, please update it immediately.
                </p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                    <label className="text-xs font-bold text-[#374151] mb-2 block uppercase tracking-wide">
                        Email
                    </label>
                    <Input
                        type="email"
                        placeholder="email@gmail.com"
                        value={formData.email}
                        onChange={(e) =>
                            setFormData({ ...formData, email: e.target.value })
                        }
                    />
                </div>

                <div>
                    <label className="text-xs font-bold text-[#374151] mb-2 block uppercase tracking-wide">
                        Current Password
                    </label>
                    <Input
                        type="password"
                        placeholder="Password"
                        value={formData.currentPassword}
                        onChange={(e) =>
                            setFormData({
                                ...formData,
                                currentPassword: e.target.value,
                            })
                        }
                        required
                    />
                </div>

                <div>
                    <label className="text-xs font-bold text-[#374151] mb-2 block uppercase tracking-wide">
                        New Password
                    </label>
                    <Input
                        type="password"
                        placeholder="Password"
                        value={formData.newPassword}
                        onChange={(e) =>
                            setFormData({
                                ...formData,
                                newPassword: e.target.value,
                            })
                        }
                        required
                    />
                </div>

                <div>
                    <label className="text-xs font-bold text-[#374151] mb-2 block uppercase tracking-wide">
                        Confirm New Password
                    </label>
                    <Input
                        type="password"
                        placeholder=" Confirm Password"
                        value={formData.confirmPassword}
                        onChange={(e) =>
                            setFormData({
                                ...formData,
                                confirmPassword: e.target.value,
                            })
                        }
                        required
                    />
                </div>

                <div className="pt-2">
                    <Button type="submit" disabled={loading}>
                        {loading ? "Processing..." : "Change Password"}
                    </Button>
                </div>

                <div className="text-center mt-4">
                    <a
                        href="/login"
                        className="text-sm text-[#2563EB] font-medium hover:underline"
                    >
                        Back to Login
                    </a>
                </div>
            </form>
        </AuthLayout>
    );
}
