import { useState, type FormEvent } from "react";
import axios from "axios";
import { useLocation, useNavigate } from "react-router-dom";
import AuthLayout from "../../layouts/AuthLayout";
import Input from "../../components/ui/Input";
import Button from "../../components/ui/Button";
import { updateCredential } from "../../features/auth/services/auth.service";

export default function UpdateCredentials() {
    const location = useLocation();
    const navigate = useNavigate();
    const { currentEmail } = location.state || {};

    const [formData, setFormData] = useState({
        email: currentEmail || "email@gmail.com",
        currentPassword: "",
        newPassword: "",
        confirmPassword: "",
    });

    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setError("");

        if (!formData.email || !formData.currentPassword || !formData.newPassword) {
            setError("Semua field wajib diisi.");
            return;
        }

        if (formData.newPassword.length < 8) {
            setError("Password baru minimal 8 karakter.");
            return;
        }

        if (formData.newPassword !== formData.confirmPassword) {
            setError("Konfirmasi password tidak sama.");
            return;
        }

        try {
            setLoading(true);
            await updateCredential({
                email: formData.email,
                currentPassword: formData.currentPassword,
                newPassword: formData.newPassword,
                confirmPassword: formData.confirmPassword,
            });

            setLoading(false);
            navigate("/login", {
                state: {
                    successMessage:
                        "Password updated. Please log in with your new credentials.",
                },
            });
        } catch (err: unknown) {
            const fallbackMessage = "Gagal memperbarui credential.";

            if (!axios.isAxiosError(err)) {
                setError(fallbackMessage);
                return;
            }

            const responseData = err.response?.data;
            if (responseData && typeof responseData === "object") {
                const message = (responseData as { message?: unknown }).message;
                if (typeof message === "string" && message.length > 0) {
                    setError(message);
                    return;
                }
            }

            setError(fallbackMessage);
        } finally {
            setLoading(false);
        }
    };

    return (
        <AuthLayout verticalAlign="top">
            <div className="mb-5 md:mb-6">
                <h1 className="text-2xl md:text-[32px] font-bold text-[#1F2937] mb-2 leading-tight">
                    Update Your Credentials
                </h1>

                <p className="text-[#6B7280] text-sm leading-relaxed max-w-[350px]">
                    Protect your account by creating a new, personalized password
                    for your profile
                </p>
            </div>

            <div className="bg-[#FFF7ED] border border-[#FFEDD5] p-4 md:p-5 rounded-lg mb-6 md:mb-8">
                <p className="text-[#9A3412] text-xs md:text-[13px] leading-relaxed">
                    <span className="font-bold">Security Action Required:</span>{" "}
                    Your current password was generated by an administrator. For
                    your protection, please update it immediately.
                </p>
            </div>

            {error && (
                <div className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-xs md:text-sm text-red-700">
                    {error}
                </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-5 md:space-y-6 pb-4">
                <div>
                    <label className="text-[11px] md:text-xs font-bold text-[#374151] mb-1 md:mb-2 block uppercase tracking-wide">
                        Email
                    </label>
                    <Input
                        type="email"
                        placeholder="email@gmail.com"
                        value={formData.email}
                        onChange={(e) =>
                            setFormData({ ...formData, email: e.target.value })
                        }
                    />
                </div>

                <div>
                    <label className="text-[11px] md:text-xs font-bold text-[#374151] mb-1 md:mb-2 block uppercase tracking-wide">
                        Current Password
                    </label>
                    <Input
                        type="password"
                        placeholder="Password"
                        value={formData.currentPassword}
                        onChange={(e) =>
                            setFormData({
                                ...formData,
                                currentPassword: e.target.value,
                            })
                        }
                        required
                    />
                </div>

                <div>
                    <label className="text-[11px] md:text-xs font-bold text-[#374151] mb-1 md:mb-2 block uppercase tracking-wide">
                        New Password
                    </label>
                    <Input
                        type="password"
                        placeholder="Password"
                        value={formData.newPassword}
                        onChange={(e) =>
                            setFormData({
                                ...formData,
                                newPassword: e.target.value,
                            })
                        }
                        required
                    />
                </div>

                <div>
                    <label className="text-[11px] md:text-xs font-bold text-[#374151] mb-1 md:mb-2 block uppercase tracking-wide">
                        Confirm New Password
                    </label>
                    <Input
                        type="password"
                        placeholder=" Confirm Password"
                        value={formData.confirmPassword}
                        onChange={(e) =>
                            setFormData({
                                ...formData,
                                confirmPassword: e.target.value,
                            })
                        }
                        required
                    />
                </div>

                <div className="pt-2">
                    <Button
                        type="submit"
                        disabled={loading}
                        className="py-2.5 md:py-3 text-sm md:text-base"
                    >
                        {loading ? "Processing..." : "Change Password"}
                    </Button>
                </div>

                <div className="text-center mt-3 md:mt-4">
                    <a
                        href="/login"
                        className="text-xs md:text-sm text-[#2563EB] font-medium hover:underline"
                    >
                        Back to Login
                    </a>
                </div>
            </form>
        </AuthLayout>
    );
}
